# vi: expandtab shiftwidth=2 softtabstop=2

# First scenario is configured as warmup and it will also tune the default ingress-controller to assign the router pods to the infra nodes
- termination: http
  connections: 200
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 5
  delay: 10s
  warmup: true

- termination: http
  connections: 200
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 5
  delay: 10s

- termination: edge
  connections: 200
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 5
  delay: 10s

- termination: reencrypt
  connections: 200
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 5
  delay: 10s

- termination: passthrough
  connections: 200
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 5
  delay: 10s
