# vi: expandtab shiftwidth=2 softtabstop=2

- termination: http
  connections: 200
  samples: 5
  duration: 3m
  path: /1024.html
  concurrency: 1024
  tool: wrk
  serverReplicas: 64
  delay: 0s
  tuningPatch: '{"spec":{"nodePlacement": {"nodeSelector": {"matchLabels": {"node-role.kubernetes.io/infra": ""}}}, "replicas": 2}}'

