# vi: expandtab shiftwidth=2 softtabstop=2

- termination: http
  connections: 1000
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 1
  tool: wrk
  serverReplicas: 45
  delay: 1s
  tuningPatch: '{"spec":{"nodePlacement": {"nodeSelector": {"matchLabels": {"node-role.kubernetes.io/infra": ""}}}, "replicas": 10}}'

- termination: edge
  connections: 1000
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 1
  tool: wrk
  serverReplicas: 45
  delay: 1s

- termination: reencrypt
  connections: 1000
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 1
  tool: wrk
  serverReplicas: 45
  delay: 1s

- termination: passthrough
  connections: 1000
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 1
  tool: wrk
  serverReplicas: 45
  delay: 1s

